# Define common configuration for resource limits
x-common-resources: &common-resources
  deploy:
    resources:
      limits:
        cpus: "2"
        memory: 8G
      reservations:
        cpus: "1"
        memory: 4G
  ulimits:
    core: 0
  environment:
    ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"

services:
  # -------------- Base Image --------------
  concolic:
    build:
      context: .
      dockerfile: concolic-common.Dockerfile
    image: concolic:latest

  # -------------- ultrajson --------------

  ultrajson:
    <<: *common-resources
    build:
      context: ./ultrajson
      dockerfile: Dockerfile
    depends_on:
      - concolic
    image: ultrajson:latest
    volumes:
      - ./ultrajson/results:/shared/:rw
    command: ["/bin/bash", "/run.sh", "concolic", "${TIMEOUT:-60s}"]

  # -------------- jansi --------------
  jansi:
    <<: *common-resources
    build:
      context: ./jansi
      dockerfile: Dockerfile
    depends_on:
      - concolic
    image: jansi:latest
    volumes:
      - ./jansi/results:/shared/:rw
    command: ["/bin/bash", "/run.sh", "concolic", "${TIMEOUT:-60s}"]

  # -------------- protobuf --------------

  protobuf:
    <<: *common-resources
    build:
      context: ./protobuf
      dockerfile: Dockerfile
    depends_on:
      - concolic
    image: protobuf:latest
    volumes:
      - ./protobuf/results:/shared/:rw
    command: ["/bin/bash", "/run.sh", "concolic", "${TIMEOUT:-60s}"]
  # -------------- py4j --------------

  py4j:
    <<: *common-resources
    build:
      context: ./py4j
      dockerfile: Dockerfile
    depends_on:
      - concolic
    image: py4j:latest
    volumes:
      - ./py4j/results:/shared/:rw
    command: ["/bin/bash", "/run.sh", "concolic", "${TIMEOUT:-60s}"]
